export const ADD_AUTHOR = 'AUTHORS/ADD_AUTHOR';
export const FETCH_AUTHORS_DATA_SUCCESS = 'AUTHORS/FETCH_AUTHORS_DATA_SUCCESS';
export const FETCH_AUTHORS_DATA_ERROR = 'AUTHORS/FETCH_AUTHORS_DATA_ERROR';
export const DELETE_AUTHOR = 'AUTHORS/DELETE_AUTHOR';
