export const ADD_AUTHOR = 'authors/ADD_AUTHOR';
export const FETCH_AUTHORS_DATA_SUCCESS = 'AUTHORS/FETCH_AUTHORS_DATA_SUCCESS';
export const FETCH_AUTHORS_DATA_ERROR = 'AUTHORS/FETCH_AUTHORS_DATA_ERROR';
