export const ADD_COURSE = 'COURSES/ADD_COURSE';
export const FETCH_COURSES_DATA_SUCCESS = 'COURSES/FETCH_COURSES_DATA_SUCCESS';
export const FETCH_COURSES_DATA_ERROR = 'COURSES/FETCH_COURSES_DATA_ERROR';
export const DELETE_COURSE = 'COURSES/DELETE_COURSE';
export const UPDATE_COURSE = 'COURSES/UPDATE_COURSE';
