export const ADD_COURSE = 'courses/ADD_COURSE';
export const FETCH_COURSES_DATA_SUCCESS = 'courses/FETCH_COURSES_DATA_SUCCESS';
export const FETCH_COURSES_DATA_ERROR = 'courses/FETCH_COURSES_DATA_ERROR';
